# Generated by Django 2.1.3 on 2018-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('body', models.TextField()),
                ('hero', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('published', models.BooleanField(default=False)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
