# Generated by Django 2.1.3 on 2018-12-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='created_at',
            new_name='published_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2),
        ),
        migrations.AddField(
            model_name='work',
            name='type',
            field=models.CharField(choices=[('CO', 'Code'), ('AR', 'Art')], default=None, max_length=2),
        ),
    ]
