# Generated by Django 2.1.3 on 2018-12-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20181202_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.Post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='related_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.Work'),
        ),
    ]
