# Generated by Django 2.1.3 on 2018-11-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='markdown',
        ),
    ]
