# Generated by Django 2.1.3 on 2018-11-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20181124_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='content.Image'),
        ),
    ]
